---
run:
  go: "1.19"

linters:
  disable-all: true
  enable:
    - containedctx
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - lll
    - makezero
    - nestif
    - nilnil
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wrapcheck
    - wsl

linters-settings:
  lll:
    line-length: 120
