---
name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make test-unit-coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/coverage.out
